### ISSUE TITLE
Update https://www.ietf.org/how/lists/discussion/ if doc is published

### ISSUE THREAD

**Issue by larseggert** [larseggert/bcp45bis#2]

**Comment by ghwood** [comment]
The [discussion list webpage on www.ietf.org](https://www.ietf.org/how/lists/discussion/ ) has been updated. 

Note: the updated version removes a link to https://github.com/ietf/saa as the "IETF Sergeants-at-Arms" reference there is (IIUC) obsolete. should it be replaced with something else?

**Comment by dhruvdhody** [comment]
Hi Greg, The Github repo is renamed and you can use -> https://github.com/ietf/Moderators

**Comment by rgwilton** [comment]
> The [discussion list webpage on www.ietf.org](https://www.ietf.org/how/lists/discussion/) has been updated.
> 
> Note: the updated version removes a link to https://github.com/ietf/saa as the "IETF Sergeants-at-Arms" reference there is (IIUC) obsolete. should it be replaced with something else?

I'm not sure anything else is required.  It looks like there is already a link to https://github.com/ietf/Moderators

**Comment by dhruvdhody** [comment]
Yes, @ghwood has done all the updates! We can close the issue!
