### ISSUE TITLE
Update https://www.ietf.org/mailman/listinfo/ietf if doc is published

### ISSUE THREAD

**Issue by larseggert** [larseggert/bcp45bis#3]

**Comment by rgwilton** [comment]
I presume that this issue is to update the definition to reference BCP 45?

**Comment by larseggert** [comment]
No, it's to update the text at that URL based on BCP45bis once that is out. Similar for #2.

**Comment by larseggert** [comment]
@ghwood could we update the URL above to point to the list charter?

**Comment by ghwood** [comment]
Updates applied here:

https://www.ietf.org/mailman/listinfo/ietf

and also here:

https://www.ietf.org/mailman/listinfo/
